### ISSUE TITLE
mappings.json is undocumented

### ISSUE THREAD

**Issue by BarDweller** [ibm-developer/ibm-cloud-spring-bind#7]
Hard to use this project without documentation describing the format of mappings.json 

Some sort of schema & example usages would go a long way to helping this to make sense (either here, or potentially in a common repo shared by this and other users of mappings.json eg, https://github.com/ibm-developer/ibm-cloud-env )

**Comment by gee4vee** [comment]
Added some more docs and pointed to the IBM Cloud Env docs to avoid duplicating those. IBM Cloud Env is the Node equivalent of this component.
